import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import "components/Nav";
import Nav from "components/Nav";
import Footer from "components/Footer";
import { Suspense } from "react";
import Loading from "./Loading";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Next FireBase APP",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Nav/>
        <Suspense fallback={<Loading/>}>
        <div className="md:mt-12  bg-gradient-radial  from-gray-200 via-gray-400 to-gray-600">{children}</div>
  </Suspense>
        <Footer/>
        </body>
    </html>
  );
}
